### ISSUE TITLE
DaisyUI Snippet not working properly (Snippets not showing up)

### ISSUE THREAD

**Issue by aidrecabrera** [emranweb/daisyui-snippet#16]
Hello! I have already enabled the extension globally. However, the snippet is not working.

![Issue](https://github.com/emranweb/daisyui-snippet/assets/61798731/39f820c4-cf02-4208-8170-72c51d9227eb)
![du-btn example issue](https://github.com/emranweb/daisyui-snippet/assets/61798731/5c05ddce-0757-45b2-851e-c27599ef0bd1)

I have also tried restarting VSCode, but it is still not working properly.

What might have caused this issue? Thank you in advance!

**Comment by emranweb** [comment]
@aidrecabrera Thanks for your feedback. I will check and update you soon.

**Comment by emranweb** [comment]
Hi @aidrecabrera. I tested the issue on my PC, but I found no problem. It works fine in all the language extensions: .tsx, .jsx, HTML, js, and ts. 

<img width="889" alt="issue" src="https://github.com/emranweb/daisyui-snippet/assets/5980298/56b255fa-2b93-47b9-ac0d-a47e96d740a5">

Here are some of my suggestions for you to take a look at.

- If you install other daisy snippets, remove all of them, including mine, and reinstall this snippet and try
- Check whether your snippets are disabled or not
- check the language support. It supports .tsx, .jsx, HTML, js, and ts. 

If you still find the issue let me know with more details so that I can check 

Thanks

**Comment by aidrecabrera** [comment]
Hello! Thank you for the response.

I tried doing your suggestions. However, it didn't work. Fortunately, I just figured out that I was running an old version of VSCode (18.01, user setup). So I tried updating my VSCode, and it's finally working!

![image](https://github.com/emranweb/daisyui-snippet/assets/61798731/1eb88f8e-7805-42e5-b713-226a4ce5bb76)

Thank you for making the extension, it helps a lot with my productivity.

Keep safe! :)
